### ISSUE TITLE
Doesn´t work with Linux

### ISSUE THREAD

**Issue by thomastieber** [maddindeiss/co2-monitor#1]
The co2monitor module works perfect on my Windows System, and i can aquire data from my aircontrol mini Monitor. When i try to use it on my Raspberry Pi 2 it always throws an error that say "Error while connecting to device! ERROR: LIBUSB_ERROR_BUSY"  The error gets thrown in the file co2monitor.js in line 61, which is in the connectToDevice function.
The Raspberry recognizes that the aircontrol mini Monitor is plugged in, when i type lsusb, the Monitor is listed, and when i replug it, the device number enumerates.
Any suggestions how to fix this Problem?

**Comment by maddindeiss** [comment]
Thanks for reporting the issue. I have tested the code on my Raspberry with Raspbian and got the same Error. I fixed that problem on linux by detaching the kernel driver from the interface.
Check out the new commit. Hope this helps

**Comment by thomastieber** [comment]
It worked on the first try with the new commit. Thank you very much.
